export const TYPES={
    SET_GAP: 'SETGAP',
    SET_ROWS: 'SETROWS',
    SET_COLS: 'SETCOLS',
    ADD_IMAGE: 'ADD_IMAGE',
    EDIT_IMAGE: 'EDIT_IMAGE',
    CHANGE_IMAGE_FOCUS: 'CHANGE_IMAGE_FOCUS',
    DELETE_IMAGE: 'DELETE_IMAGE',
}
